modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL=""
description='''Adds RGB lightbulbs and FE cables compatible with Create Crafts & Additions via Forge Energy.'''
authors="Electric RGB"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"
